import type { Product } from './types';

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Smart LED TV 55"',
    image: 'https://placehold.co/600x400',
    price: 499.99,
    description: 'A stunning 55-inch 4K Smart LED TV with HDR, providing brilliant colors and deep contrasts. Access all your favorite streaming apps directly on the TV.',
    category: 'TVs and Home Theatres',
  },
  {
    id: '2',
    name: 'Surround Sound System',
    image: 'https://placehold.co/600x400',
    price: 349.0,
    description: 'Immersive 5.1 channel surround sound system. Perfect for movies, music, and gaming. Includes a powerful subwoofer for deep bass.',
    category: 'TVs and Home Theatres',
  },
  {
    id: '3',
    name: '1.5 Ton Split AC',
    image: 'https://placehold.co/600x400',
    price: 699.99,
    description: 'Energy-efficient 1.5-ton split air conditioner with inverter technology. Cools your room quickly and quietly.',
    category: 'Home Appliances',
  },
  {
    id: '4',
    name: 'Front Load Washing Machine',
    image: 'https://placehold.co/600x400',
    price: 599.0,
    description: '7kg fully automatic front load washing machine with 12 wash programs. Gentle on clothes, tough on stains.',
    category: 'Home Appliances',
  },
  {
    id: '5',
    name: 'Double Door Refrigerator',
    image: 'https://placehold.co/600x400',
    price: 799.0,
    description: '250L frost-free double door refrigerator. Keeps your food fresh for longer with its advanced cooling technology.',
    category: 'Home Appliances',
  },
  {
    id: '6',
    name: 'Latest Smartphone Pro',
    image: 'https://placehold.co/600x400',
    price: 999.0,
    description: 'The latest flagship smartphone with a stunning OLED display, professional-grade cameras, and lightning-fast performance.',
    category: 'Mobiles',
  },
  {
    id: '7',
    name: 'Mid-Range Smartphone',
    image: 'https://placehold.co/600x400',
    price: 399.0,
    description: 'A powerful mid-range phone that offers a premium experience without the premium price tag. Great camera and all-day battery life.',
    category: 'Mobiles',
  },
  {
    id: '8',
    name: 'Noise-Cancelling Headphones',
    image: 'https://placehold.co/600x400',
    price: 249.99,
    description: 'Over-ear wireless headphones with active noise cancellation. Enjoy your music without distractions. Long-lasting battery and comfortable design.',
    category: 'Accessories',
  },
  {
    id: '9',
    name: 'Wireless Power Bank',
    image: 'https://placehold.co/600x400',
    price: 49.99,
    description: '10,000mAh portable power bank with wireless charging capabilities. Charge your devices on the go, no cables needed.',
    category: 'Accessories',
  },
];
